name: Build server Docker images

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag used for a manual build'
        required: true
        default: '0.0.0-dev'
      api_version:
        description: 'API image tag from the current owner rustdesk-api fork'
        required: true
        default: '0.0.0-dev'
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'

env:
  CARGO_TERM_COLOR: always
  LATEST_TAG: latest
  API_VERSION: ${{ github.event.inputs.api_version || github.ref_name }}
  IMAGE_TAG: ${{ github.event.inputs.image_tag || github.ref_name }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE || secrets.DOCKER_USERNAME }}

permissions:
  contents: read
  packages: write # So need to set "secrets.GITHUB_TOKEN"

jobs:

  # Binary build
  build:
    name: Build - ${{ matrix.job.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        job:
          - { name: "amd64",   target: "x86_64-unknown-linux-musl" }
          - { name: "arm64v8", target: "aarch64-unknown-linux-musl" }
          - { name: "armv7",   target: "armv7-unknown-linux-musleabihf" }
          - { name: "i386",    target: "i686-unknown-linux-musl" }
          #- { name: "amd64fb", target: "x86_64-unknown-freebsd" }

    steps:
      - name: Validate versions
        run: |
          VERSION_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z]+([.-][0-9A-Za-z]+)*)?$'
          if [[ ! "$IMAGE_TAG" =~ $VERSION_PATTERN ]]; then
            echo "Invalid server version: $IMAGE_TAG"
            exit 1
          fi
          if [[ ! "$API_VERSION" =~ $VERSION_PATTERN ]]; then
            echo "Invalid API version: $API_VERSION"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: ${{ matrix.job.target }}
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.job.name }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=${{ matrix.job.target }}
          use-cross: true

      - name: Exec chmod
        run: chmod -v a+x target/${{ matrix.job.target }}/release/*

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-${{ matrix.job.name }}
          path: |
            target/${{ matrix.job.target }}/release/hbbr
            target/${{ matrix.job.target }}/release/hbbs
            target/${{ matrix.job.target }}/release/rustdesk-utils
          if-no-files-found: error

  # Build and push single-arch Docker images to ghcr.io
  create-s6-overlay-images:
    name: Docker push s6-overlay - ${{ matrix.job.name }}
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        job:
          - { name: "amd64",   docker_platform: "linux/amd64",  s6_platform: "x86_64" }
          - { name: "arm64v8", docker_platform: "linux/arm64",  s6_platform: "aarch64" }
          - { name: "armv7",   docker_platform: "linux/arm/v7", s6_platform: "armhf" }
#          - { name: "i386",    docker_platform: "linux/386",    s6_platform: "i686" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-linux-${{ matrix.job.name }}
          path: docker/rootfs/usr/bin
          merge-multiple: true

      - name: Make binaries executable
        run: chmod -v a+x docker/rootfs/usr/bin/*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-s6

      - name: Get git tag
        id: vars
        run: |
          T="${IMAGE_TAG}-api-${API_VERSION}"
          RESOLVED_API_IMAGE="ghcr.io/${{ github.repository_owner }}/rustdesk-api:${API_VERSION}"
          echo "GIT_TAG=$T" >> $GITHUB_ENV
          echo "API_IMAGE_RESOLVED=$RESOLVED_API_IMAGE" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "./docker"
          platforms: ${{ matrix.job.docker_platform }}
          push: true
          provenance: false
          build-args: |
            S6_ARCH=${{ matrix.job.s6_platform }}
            API_IMAGE=${{ env.API_IMAGE_RESOLVED }}
          tags: |
            ghcr.io/${{ github.repository }}-s6:${{ env.GIT_TAG }}-${{ matrix.job.name }}
            ghcr.io/${{ github.repository }}-s6:${{ env.LATEST_TAG }}-${{ matrix.job.name }}
            ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' && format('{0}/rustdesk-server-s6:{1}-{2}', env.DOCKERHUB_NAMESPACE, env.GIT_TAG, matrix.job.name) || '' }}
            ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' && format('{0}/rustdesk-server-s6:latest-{1}', env.DOCKERHUB_NAMESPACE, matrix.job.name) || '' }}
          labels: ${{ steps.meta.outputs.labels }}

  # Set up minifest and tag for pushed image
  create-s6-overlay-images-manifest:
    name: Manifest for s6-overlay images
    needs: create-s6-overlay-images
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Get git tag
        id: vars
        run: |
          T="${IMAGE_TAG}-api-${API_VERSION}"
          echo "GIT_TAG=$T" >> $GITHUB_ENV

      - name: Create GHCR manifests
        env:
          IMAGE: ghcr.io/${{ github.repository }}-s6
        run: |
          docker buildx imagetools create --tag "$IMAGE:$GIT_TAG" "$IMAGE:$GIT_TAG-amd64" "$IMAGE:$GIT_TAG-arm64v8" "$IMAGE:$GIT_TAG-armv7"
          docker buildx imagetools create --tag "$IMAGE:$LATEST_TAG" "$IMAGE:$LATEST_TAG-amd64" "$IMAGE:$LATEST_TAG-arm64v8" "$IMAGE:$LATEST_TAG-armv7"

      - name: Create Docker Hub manifests
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        env:
          IMAGE: ${{ env.DOCKERHUB_NAMESPACE }}/rustdesk-server-s6
        run: |
          docker buildx imagetools create --tag "$IMAGE:$GIT_TAG" "$IMAGE:$GIT_TAG-amd64" "$IMAGE:$GIT_TAG-arm64v8" "$IMAGE:$GIT_TAG-armv7"
          docker buildx imagetools create --tag "$IMAGE:$LATEST_TAG" "$IMAGE:$LATEST_TAG-amd64" "$IMAGE:$LATEST_TAG-arm64v8" "$IMAGE:$LATEST_TAG-armv7"

  # Build and push single-arch Docker images to ghcr.io
  create-classic-images:
    name: Docker push classic - ${{ matrix.job.name }}
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        job:
          - { name: "amd64",   docker_platform: "linux/amd64" }
          - { name: "arm64v8", docker_platform: "linux/arm64" }
          - { name: "armv7",   docker_platform: "linux/arm/v7" }
          - { name: "i386",    docker_platform: "linux/386" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-linux-${{ matrix.job.name }}
          path: docker-classic
          merge-multiple: true

      - name: Make binaries executable
        run: chmod -v a+x docker-classic/*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Get git tag
        id: vars
        run: |
          T="${IMAGE_TAG}"
          echo "GIT_TAG=$T" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "./docker-classic"
          platforms: ${{ matrix.job.docker_platform }}
          push: true
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.GIT_TAG }}-${{ matrix.job.name }}
            ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}-${{ matrix.job.name }}
            ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' && format('{0}/rustdesk-server:{1}-{2}', env.DOCKERHUB_NAMESPACE, env.GIT_TAG, matrix.job.name) || '' }}
            ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' && format('{0}/rustdesk-server:latest-{1}', env.DOCKERHUB_NAMESPACE, matrix.job.name) || '' }}
          labels: ${{ steps.meta.outputs.labels }}

  # Set up minifest and tag for pushed image
  create-classic-images-manifest:
    name: Manifest for classic images
    needs: create-classic-images
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Get git tag
        id: vars
        run: |
          T="${IMAGE_TAG}"
          echo "GIT_TAG=$T" >> $GITHUB_ENV

      - name: Create GHCR manifests
        env:
          IMAGE: ghcr.io/${{ github.repository }}
        run: |
          docker buildx imagetools create --tag "$IMAGE:$GIT_TAG" "$IMAGE:$GIT_TAG-amd64" "$IMAGE:$GIT_TAG-arm64v8" "$IMAGE:$GIT_TAG-armv7" "$IMAGE:$GIT_TAG-i386"
          docker buildx imagetools create --tag "$IMAGE:$LATEST_TAG" "$IMAGE:$LATEST_TAG-amd64" "$IMAGE:$LATEST_TAG-arm64v8" "$IMAGE:$LATEST_TAG-armv7" "$IMAGE:$LATEST_TAG-i386"

      - name: Create Docker Hub manifests
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        env:
          IMAGE: ${{ env.DOCKERHUB_NAMESPACE }}/rustdesk-server
        run: |
          docker buildx imagetools create --tag "$IMAGE:$GIT_TAG" "$IMAGE:$GIT_TAG-amd64" "$IMAGE:$GIT_TAG-arm64v8" "$IMAGE:$GIT_TAG-armv7" "$IMAGE:$GIT_TAG-i386"
          docker buildx imagetools create --tag "$IMAGE:$LATEST_TAG" "$IMAGE:$LATEST_TAG-amd64" "$IMAGE:$LATEST_TAG-arm64v8" "$IMAGE:$LATEST_TAG-armv7" "$IMAGE:$LATEST_TAG-i386"
