name: test

on:
  workflow_dispatch:
  push:
    branches: [ "forapi" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "forapi" ]
    paths-ignore:
      - '**/README.md'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: '1.90.0'
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: '1.90.0'
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: '1.90.0'
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Generate version module
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --package hbbs
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --package hbbs -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: '1.90.0'
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --package hbbs --all-targets --no-deps -- -D warnings
